# Generated by Django 5.0.3 on 2024-03-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfgenerator', '0003_alter_report_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='logo',
            field=models.FileField(upload_to='uploads/logos/'),
        ),
    ]
