# Generated by Django 5.0.3 on 2024-03-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfgenerator', '0004_alter_report_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_pdf_file',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
